#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

#define _QWERTY 0
#define _GAME_NUMPAD 1
#define _FUNCTION 2
#define _ADJUST 16

enum custom_keycodes {
  QWERTY = SAFE_RANGE,
  GAME_NUMPAD,
  FUNCTION,
  ADJUST
};


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[_QWERTY] = LAYOUT_4key_2u_inner(
    //┌────────┬─────────┬─────────┬──────────┬───────┬────────┬──────────┐               ┌──────────┬───────┬───────┬────────┬────────┬──────────┬─────────┐
        KC_EQL,   KC_1,     KC_2,     KC_3,     KC_4,   KC_5,     KC_ESC,                   KC_PGUP,  KC_6,   KC_7,   KC_8,     KC_9,     KC_0,     KC_MINS,
    //├────────┼─────────┼─────────┼──────────┼───────┼────────┼──────────┤               ├──────────┼───────┼───────┼────────┼────────┼──────────┼─────────┤
        KC_TAB,   KC_Q,     KC_W,     KC_E,     KC_R,   KC_T,     KC_HOME,                  KC_PGDN,  KC_Y,   KC_U,   KC_I,     KC_O,     KC_P,     KC_BSLS, 
    //├────────┼─────────┼─────────┼──────────┼───────┼────────┼──────────┤               ├──────────┼───────┼───────┼────────┼────────┼──────────┼─────────┤
        KC_CAPS,  KC_A,     KC_S,     KC_D,     KC_F,   KC_G,     KC_LALT,                  KC_RGUI,  KC_H,   KC_J,   KC_K,     KC_L,     KC_SCLN,  KC_QUOT, 
    //├────────┼─────────┼─────────┼──────────┼───────┼────────┼────────┬─┴──────┐  ┌─────┴──┬───────┼───────┼───────┼────────┼────────┼──────────┼─────────┤
        KC_LSFT,  KC_Z,     KC_X,     KC_C,     KC_V,   KC_B,             KC_LCTL,    KC_RCTL,        KC_N,   KC_M,   KC_COMM,  KC_DOT,   KC_SLSH,  KC_RSFT, 
    //├────────┼─────────┼─────────┼──────────┼───────┼────────┤        ├────────┤  ├────────┤       ├───────┼───────┼────────┼────────┼──────────┼─────────┤
        KC_GRV,   KC_BSLS,  KC_LEFT,  KC_RGHT,          TT(1),  KC_BSPC,  KC_DEL,     KC_ENT,  KC_SPC, TT(2),          KC_UP,  KC_DOWN,  KC_LBRC,  KC_RBRC
    //└────────┴─────────┴─────────┴──────────┘       └────────┴────────┴────────┘  └────────┴───────┴───────┘       └────────┴────────┴──────────┴─────────┘
        ),
	[_GAME_NUMPAD] = LAYOUT_4key_2u_inner(
  //┌────────┬─────────┬─────────┬──────────┬────────┬────────┬──────────┐               ┌──────────┬────────┬────────┬────────┬────────┬──────────┬─────────┐
      KC_ESC,   KC_TRNS, KC_TRNS, KC_TRNS,    KC_TRNS, KC_TRNS, KC_TRNS,                  KC_TRNS,    KC_TRNS, KC_TRNS, KC_TRNS, KC_PSLS, KC_PAST,    KC_PMNS, 
  //├────────┼─────────┼─────────┼──────────┼────────┼────────┼──────────┤               ├──────────┼────────┼────────┼────────┼────────┼──────────┼─────────┤
      KC_TRNS,  KC_TRNS, KC_UP,   KC_TRNS,    KC_TRNS, KC_TRNS, KC_TRNS,                  KC_TRNS,    KC_TRNS, KC_TRNS, KC_P7,   KC_P8,   KC_P9,      KC_PPLS,
  //├────────┼─────────┼─────────┼──────────┼────────┼────────┼──────────┤               ├──────────┼────────┼────────┼────────┼────────┼──────────┼─────────┤ 
      KC_TRNS,  KC_LEFT, KC_DOWN, KC_RGHT,    KC_TRNS, KC_TRNS, KC_TRNS,                  KC_TRNS,    KC_TRNS, KC_TRNS, KC_P4,   KC_P5,   KC_P6,      KC_PCMM,
  //├────────┼─────────┼─────────┼──────────┼────────┼────────┼────────┬─┴──────┐  ┌─────┴──┬───────┼────────┼────────┼────────┼────────┼──────────┼─────────┤ 
      KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS,    KC_TRNS, KC_TRNS,         KC_TRNS,    KC_TRNS,          KC_TRNS, KC_TRNS, KC_P1,   KC_P2,   KC_P3,      KC_PEQL,
  //├────────┼─────────┼─────────┼──────────┼────────┼────────┤        ├────────┤  ├────────┤       ├────────┼────────┼────────┼────────┼──────────┼─────────┤ 
      KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS,            KC_TRNS,  KC_SPC, KC_TRNS,    KC_TRNS, KC_TRNS, KC_TRNS,          KC_P0,  KC_P0,    KC_PDOT,    KC_PENT
  //└────────┴─────────┴─────────┴──────────┘        └────────┴────────┴────────┘  └────────┴───────┴────────┘        └────────┴────────┴──────────┴─────────┘
    ),
	[_FUNCTION] = LAYOUT_4key_2u_inner(
  //┌────────┬─────────┬─────────┬──────────┬────────┬────────┬──────────┐               ┌──────────┬────────┬────────┬────────┬────────┬──────────┬─────────┐
      KC_ESC,   KC_F1,    KC_F2,    KC_F3,    KC_F4,    KC_F5,    KC_F6,                   KC_F7,     KC_F8,    KC_F9,   KC_F10, KC_F11,  KC_F12,     KC_PSCR, 
  //├────────┼─────────┼─────────┼──────────┼────────┼────────┼──────────┤               ├──────────┼────────┼────────┼────────┼────────┼──────────┼─────────┤
      KC_TRNS, KC_TRNS,   KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS,  RGB_TOG,                    RGB_TOG,  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,  KC_TRNS, 
  //├────────┼─────────┼─────────┼──────────┼────────┼────────┼──────────┤               ├──────────┼────────┼────────┼────────┼────────┼──────────┼─────────┤ 
      KC_TRNS, KC_TRNS,   KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS,  RGB_MODE_FORWARD,           KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,  KC_TRNS, 
  //├────────┼─────────┼─────────┼──────────┼────────┼────────┼────────┬─┴──────┐  ┌─────┴──┬───────┼────────┼────────┼────────┼────────┼──────────┼─────────┤ 
      KC_TRNS, KC_TRNS, KC_TRNS,    KC_TRNS, KC_TRNS, KC_TRNS,          KC_TRNS,    KC_TRNS,          KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,  KC_TRNS, 
  //├────────┼─────────┼─────────┼──────────┼────────┼────────┤        ├────────┤  ├────────┤       ├────────┼────────┼────────┼────────┼──────────┼─────────┤ 
      KC_TRNS, KC_TRNS, KC_TRNS,    KC_TRNS,          KC_TRNS, KC_TRNS, KC_TRNS,    KC_TRNS, KC_TRNS, KC_TRNS,          KC_TRNS, KC_TRNS, KC_TRNS,  KC_TRNS
  //└────────┴─────────┴─────────┴──────────┘        └────────┴────────┴────────┘  └────────┴───────┴────────┘        └────────┴────────┴──────────┴─────────┘
    )
};



void persistent_default_layer_set(uint16_t default_layer) {
  eeconfig_update_default_layer(default_layer);
  default_layer_set(default_layer);
}

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
  switch (keycode) {
    case QWERTY:
      if (record->event.pressed) {
        set_single_persistent_default_layer(_QWERTY);
      }
      return false;
      break;
    case GAME_NUMPAD:
      if (record->event.pressed) {
        layer_on(_GAME_NUMPAD);
        update_tri_layer(_GAME_NUMPAD, _FUNCTION, _ADJUST);
      } else {
        layer_off(_GAME_NUMPAD);
        update_tri_layer(_GAME_NUMPAD, _FUNCTION, _ADJUST);
      }
      return false;
      break;
    case FUNCTION:
      if (record->event.pressed) {
        layer_on(_FUNCTION);
        update_tri_layer(_GAME_NUMPAD, _FUNCTION, _ADJUST);
      } else {
        layer_off(_FUNCTION);
        update_tri_layer(_GAME_NUMPAD, _FUNCTION, _ADJUST);
      }
      return false;
      break;
    case ADJUST:
      if (record->event.pressed) {
        layer_on(_ADJUST);
      } else {
        layer_off(_ADJUST);
      }
      return false;
      break;
  }
  return true;
}

// set rgb layer indicators
const rgblight_segment_t PROGMEM game_num_layer[] = RGBLIGHT_LAYER_SEGMENTS(
   {0, 42, HSV_TEAL} 
    );

const rgblight_segment_t PROGMEM function_layer[] = RGBLIGHT_LAYER_SEGMENTS(
   {0, 42, HSV_MAGENTA} 
    );  

// define array of layers. Later layers take precedence
const rgblight_segment_t* const PROGMEM my_rgb_layers[] = RGBLIGHT_LAYERS_LIST(
    game_num_layer,
    function_layer
    );

#ifdef RGBLIGHT_ENABLE
void keyboard_post_init_user(void) {
  rgblight_toggle();
  rgblight_sethsv(0,0,0);
  // Enable the LED layers
  rgblight_layers = my_rgb_layers; 
  rgblight_enable_noeeprom();
}
#endif

layer_state_t layer_state_set_user(layer_state_t state) {
    rgblight_set_layer_state(0, layer_state_cmp(state, _GAME_NUMPAD));
    rgblight_set_layer_state(1, layer_state_cmp(state, _FUNCTION));
    return state;
}